options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    develop:
      - step:
          name: build and publish the hspc-ubuntu-base image
          script:
            # get the ci scripts
            - git clone https://bitbucket.org/hspconsortium/sandbox-ci.git
            - export IMAGE_REPO=hspconsortium
            - export IMAGE_NAME=hspc-ubuntu-base
            - export IMAGE_VERSION=latest
            - export IMAGE_COORDINATES="$IMAGE_REPO/$IMAGE_NAME:$IMAGE_VERSION"; echo $IMAGE_COORDINATES
            # build and publish the docker image
            - . sandbox-ci/bitbucket-pipeline-scripts/docker-build-and-push.sh $IMAGE_COORDINATES
    master:
      - step:
          name: build and publish the hspc-ubuntu-base image
          script:
            # get the ci scripts
            - git clone https://bitbucket.org/hspconsortium/sandbox-ci.git
            - export IMAGE_REPO=hspconsortium
            - export IMAGE_NAME=hspc-ubuntu-base
            - export IMAGE_VERSION=0.1.0
            - export IMAGE_COORDINATES="$IMAGE_REPO/$IMAGE_NAME:$IMAGE_VERSION"; echo $IMAGE_COORDINATES
            # build and publish the docker image
            - . sandbox-ci/bitbucket-pipeline-scripts/docker-build-and-push.sh $IMAGE_COORDINATES
    feature/*:
      - step:
          script:
            - echo "all good"
    release/*:
      - step:
          script:
            - echo "all good"
    hotfix/*:
      - step:
          script:
            - echo "all good"
