options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    develop:
      - step:
          name: build and publish the hspc-ubuntu-base image
          script:
            - export IMAGE_REPO=hspconsortium
            - export IMAGE_NAME=hspc-ubuntu-base
            - export IMAGE_VERSION=latest
            - export IMAGE_COORDINATES="$IMAGE_REPO/$IMAGE_NAME:$IMAGE_VERSION"
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -t $IMAGE_COORDINATES .
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_COORDINATES
    master:
      - step:
          name: build and publish the hspc-ubuntu-base image
          script:
            - export IMAGE_REPO=hspconsortium
            - export IMAGE_NAME=hspc-ubuntu-base
            - export IMAGE_VERSION=0.1.0
            - export IMAGE_COORDINATES="$IMAGE_REPO/$IMAGE_NAME:$IMAGE_VERSION"
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -t $IMAGE_COORDINATES .
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_COORDINATES
    feature/*:
      - step:
          script:
            - echo "all good"
    release/*:
      - step:
          script:
            - echo "all good"
    hotfix/*:
      - step:
          script:
            - echo "all good"
